// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PharmacyPos.Api.Data;

#nullable disable

namespace PharmacyPos.Api.Migrations
{
    [DbContext(typeof(PharmacyDbContext))]
    [Migration("20260914093650_InitialCatalogue")]
    partial class InitialCatalogue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PharmacyPos.Api.Catalogue.DosageForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("dosage_forms", null, t =>
                        {
                            t.HasCheckConstraint("ck_form_name", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("PharmacyPos.Api.Catalogue.GenericIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("generic_ingredients", null, t =>
                        {
                            t.HasCheckConstraint("ck_generic_name", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("PharmacyPos.Api.Catalogue.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("manufacturers", null, t =>
                        {
                            t.HasCheckConstraint("ck_manufacturer_name", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("PharmacyPos.Api.Catalogue.Medicine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("base_unit");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("brand_name");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("classification");

                    b.Property<Guid>("DosageFormId")
                        .HasColumnType("uuid")
                        .HasColumnName("dosage_form_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manufacturer_id");

                    b.HasKey("Id");

                    b.HasIndex("BrandName");

                    b.HasIndex("DosageFormId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("medicines", null, t =>
                        {
                            t.HasCheckConstraint("ck_medicine_base_unit", "base_unit = 'Tablet'");

                            t.HasCheckConstraint("ck_medicine_brand", "length(btrim(brand_name)) > 0");

                            t.HasCheckConstraint("ck_medicine_classification", "classification IN ('Otc', 'Prescription')");
                        });
                });

            modelBuilder.Entity("PharmacyPos.Api.Catalogue.MedicineIngredient", b =>
                {
                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<Guid>("GenericIngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("generic_ingredient_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("StrengthUnit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("strength_unit");

                    b.Property<decimal>("StrengthValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("strength_value");

                    b.HasKey("MedicineId", "GenericIngredientId");

                    b.HasIndex("GenericIngredientId");

                    b.HasIndex("MedicineId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("medicine_ingredients", null, t =>
                        {
                            t.HasCheckConstraint("ck_ingredient_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_ingredient_strength", "strength_value > 0");

                            t.HasCheckConstraint("ck_ingredient_unit", "length(btrim(strength_unit)) > 0");
                        });
                });

            modelBuilder.Entity("PharmacyPos.Api.Catalogue.Medicine", b =>
                {
                    b.HasOne("PharmacyPos.Api.Catalogue.DosageForm", "DosageForm")
                        .WithMany()
                        .HasForeignKey("DosageFormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmacyPos.Api.Catalogue.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DosageForm");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PharmacyPos.Api.Catalogue.MedicineIngredient", b =>
                {
                    b.HasOne("PharmacyPos.Api.Catalogue.GenericIngredient", "GenericIngredient")
                        .WithMany()
                        .HasForeignKey("GenericIngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmacyPos.Api.Catalogue.Medicine", "Medicine")
                        .WithMany("Ingredients")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GenericIngredient");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("PharmacyPos.Api.Catalogue.Medicine", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
