// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PharmacyPos.Api.Data;

#nullable disable

namespace PharmacyPos.Api.Migrations
{
    [DbContext(typeof(PharmacyDbContext))]
    [Migration("20260915134438_DiscountOffers")]
    partial class DiscountOffers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PharmacyPos.Api.Catalogue.DosageForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("dosage_forms", null, t =>
                        {
                            t.HasCheckConstraint("ck_form_name", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("PharmacyPos.Api.Catalogue.GenericIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("generic_ingredients", null, t =>
                        {
                            t.HasCheckConstraint("ck_generic_name", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("PharmacyPos.Api.Catalogue.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("manufacturers", null, t =>
                        {
                            t.HasCheckConstraint("ck_manufacturer_name", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("PharmacyPos.Api.Catalogue.Medicine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("base_unit");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("brand_name");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("classification");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CreationRequestHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("creation_request_hash");

                    b.Property<Guid>("DosageFormId")
                        .HasColumnType("uuid")
                        .HasColumnName("dosage_form_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("review_note");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Approved")
                        .HasColumnName("review_status");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("reviewed_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("BrandName");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DosageFormId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("medicines", null, t =>
                        {
                            t.HasCheckConstraint("ck_medicine_base_unit", "base_unit IN ('Tablet', 'Capsule', 'Bottle', 'Tube', 'Vial', 'Ampoule', 'Sachet', 'Piece')");

                            t.HasCheckConstraint("ck_medicine_brand", "length(btrim(brand_name)) > 0");

                            t.HasCheckConstraint("ck_medicine_classification", "classification IN ('Otc', 'Prescription')");

                            t.HasCheckConstraint("ck_medicine_review", "review_status IN ('Approved', 'PendingReview', 'Rejected')");
                        });
                });

            modelBuilder.Entity("PharmacyPos.Api.Catalogue.MedicineBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("batch_number");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<DateOnly?>("ManufacturingDate")
                        .HasColumnType("date")
                        .HasColumnName("manufacturing_date");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId", "BatchNumber")
                        .IsUnique();

                    b.ToTable("medicine_batches", null, t =>
                        {
                            t.HasCheckConstraint("ck_batch_dates", "manufacturing_date IS NULL OR manufacturing_date <= expiry_date");

                            t.HasCheckConstraint("ck_batch_number", "length(btrim(batch_number)) > 0");
                        });
                });

            modelBuilder.Entity("PharmacyPos.Api.Catalogue.MedicineIngredient", b =>
                {
                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<Guid>("GenericIngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("generic_ingredient_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("StrengthUnit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("strength_unit");

                    b.Property<decimal>("StrengthValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("strength_value");

                    b.HasKey("MedicineId", "GenericIngredientId");

                    b.HasIndex("GenericIngredientId");

                    b.HasIndex("MedicineId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("medicine_ingredients", null, t =>
                        {
                            t.HasCheckConstraint("ck_ingredient_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_ingredient_strength", "strength_value > 0");

                            t.HasCheckConstraint("ck_ingredient_unit", "length(btrim(strength_unit)) > 0");
                        });
                });

            modelBuilder.Entity("PharmacyPos.Api.Sales.ChargeMedicine", b =>
                {
                    b.Property<Guid>("ChargeRuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid");

                    b.HasKey("ChargeRuleId", "MedicineId");

                    b.HasIndex("MedicineId");

                    b.ToTable("charge_medicines", (string)null);
                });

            modelBuilder.Entity("PharmacyPos.Api.Sales.ChargeRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllMedicines")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StoppedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasFilter("\"StoppedAt\" IS NULL");

                    b.HasIndex("StoppedBy");

                    b.ToTable("charge_rules", null, t =>
                        {
                            t.HasCheckConstraint("ck_charge_kind", "\"Kind\" IN ('Percentage', 'PerUnit', 'PerMedicine')");

                            t.HasCheckConstraint("ck_charge_value", "\"Value\" > 0 AND \"Value\" <= 1000000 AND (\"Kind\" <> 'Percentage' OR \"Value\" <= 100)");
                        });
                });

            modelBuilder.Entity("PharmacyPos.Api.Sales.OfferRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("MedicineId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MinimumSubtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StoppedBy")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Units")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("MedicineId");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasFilter("\"StoppedAt\" IS NULL");

                    b.HasIndex("StoppedBy");

                    b.ToTable("offer_rules", null, t =>
                        {
                            t.HasCheckConstraint("ck_offer_dates", "\"EndDate\" IS NULL OR \"EndDate\" >= \"StartDate\"");

                            t.HasCheckConstraint("ck_offer_kind", "\"Kind\" IN ('Percentage', 'Fixed')");

                            t.HasCheckConstraint("ck_offer_minimum", "\"MinimumSubtotal\" BETWEEN 0 AND 1000000000 AND (\"MedicineId\" IS NULL OR \"MinimumSubtotal\" = 0)");

                            t.HasCheckConstraint("ck_offer_pack_scope", "(\"MedicineId\" IS NOT NULL AND \"Kind\" = 'Fixed') OR (\"Unit\" = 'Piece' AND \"Units\" = 1)");

                            t.HasCheckConstraint("ck_offer_unit", "\"Unit\" IN ('Piece', 'Strip', 'Box') AND \"Units\" BETWEEN 1 AND 1000000 AND (\"Unit\" <> 'Piece' OR \"Units\" = 1)");

                            t.HasCheckConstraint("ck_offer_value", "\"Value\" > 0 AND \"Value\" <= 1000000 AND (\"Kind\" <> 'Percentage' OR \"Value\" <= 100)");
                        });
                });

            modelBuilder.Entity("PharmacyPos.Api.Stock.ReceivingMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("PostedByUserId");

                    b.HasIndex("ReceiptId")
                        .IsUnique();

                    b.HasIndex("RevisionId", "ReceiptId");

                    b.ToTable("receiving_movements", null, t =>
                        {
                            t.HasCheckConstraint("ck_receiving_movement_quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("PharmacyPos.Api.Stock.StockDisposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DisposedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisposedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("VisibleUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DisposedByUserId");

                    b.HasIndex("ReceiptId")
                        .IsUnique();

                    b.HasIndex("VisibleUntil");

                    b.ToTable("stock_disposals", null, t =>
                        {
                            t.HasCheckConstraint("ck_disposal_quantity", "\"Quantity\" > 0");

                            t.HasCheckConstraint("ck_disposal_retention", "\"VisibleUntil\" > \"DisposedAt\"");
                        });
                });

            modelBuilder.Entity("PharmacyPos.Api.Stock.StockExportEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.ToTable("stock_export_events", (string)null);
                });

            modelBuilder.Entity("PharmacyPos.Api.Stock.StockReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentRevision")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("stock_receipts", null, t =>
                        {
                            t.HasCheckConstraint("ck_receipt_revision", "\"CurrentRevision\" > 0");
                        });
                });

            modelBuilder.Entity("PharmacyPos.Api.Stock.StockReceiptRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutomaticApproval")
                        .HasColumnType("boolean");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Boxes")
                        .HasColumnType("integer");

                    b.Property<int>("BoxesPerCarton")
                        .HasColumnType("integer");

                    b.Property<int>("Cartons")
                        .HasColumnType("integer");

                    b.Property<string>("CorrectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ManufacturingDate")
                        .HasColumnType("date");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MrpAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<string>("MrpUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("MrpUnits")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("MrpVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MrpVerifiedByUserId")
                        .HasColumnType("text");

                    b.Property<int>("Pieces")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ReceivedDate")
                        .HasColumnType("date");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedByUserId")
                        .HasColumnType("text");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Strips")
                        .HasColumnType("integer");

                    b.Property<int>("StripsPerBox")
                        .HasColumnType("integer");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("TotalUnits")
                        .HasColumnType("bigint");

                    b.Property<int>("UnitsPerBox")
                        .HasColumnType("integer");

                    b.Property<int>("UnitsPerStrip")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MedicineId");

                    b.HasIndex("MrpVerifiedByUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("ReceiptId", "Revision")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("stock_receipt_revisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_receiving_dates", "\"ManufacturingDate\" IS NULL OR \"ManufacturingDate\" <= \"ExpiryDate\"");

                            t.HasCheckConstraint("ck_receiving_pack", "\"UnitsPerStrip\" >= 0 AND \"StripsPerBox\" >= 0 AND \"UnitsPerBox\" BETWEEN 1 AND 1000000 AND \"BoxesPerCarton\" BETWEEN 1 AND 1000000 AND ((\"UnitsPerStrip\" = 0 AND \"StripsPerBox\" = 0 AND \"Strips\" = 0) OR (\"UnitsPerStrip\" > 0 AND \"StripsPerBox\" > 0 AND \"UnitsPerStrip\"::bigint * \"StripsPerBox\" = \"UnitsPerBox\"))");

                            t.HasCheckConstraint("ck_receiving_price", "\"MrpAmount\" > 0 AND \"MrpUnit\" IN ('Piece', 'Strip', 'Box') AND \"MrpUnits\" = CASE \"MrpUnit\" WHEN 'Piece' THEN 1 WHEN 'Strip' THEN \"UnitsPerStrip\" ELSE \"UnitsPerBox\" END AND \"MrpUnits\" > 0");

                            t.HasCheckConstraint("ck_receiving_quantity", "\"Pieces\" >= 0 AND \"Strips\" >= 0 AND \"Boxes\" >= 0 AND \"Cartons\" >= 0 AND \"TotalUnits\" BETWEEN 1 AND 1000000000 AND \"TotalUnits\" = \"Pieces\"::bigint + \"Strips\"::bigint * \"UnitsPerStrip\" + (\"Boxes\"::bigint + \"Cartons\"::bigint * \"BoxesPerCarton\") * \"UnitsPerBox\"");

                            t.HasCheckConstraint("ck_receiving_revision", "\"Revision\" > 0");

                            t.HasCheckConstraint("ck_receiving_status", "\"Status\" IN ('PendingApproval', 'Returned', 'Superseded', 'Approved')");
                        });
                });

            modelBuilder.Entity("PharmacyPos.Api.Stock.StockReviewEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("RevisionId");

                    b.ToTable("stock_review_events", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmacyPos.Api.Catalogue.Medicine", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PharmacyPos.Api.Catalogue.DosageForm", "DosageForm")
                        .WithMany()
                        .HasForeignKey("DosageFormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmacyPos.Api.Catalogue.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DosageForm");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PharmacyPos.Api.Catalogue.MedicineBatch", b =>
                {
                    b.HasOne("PharmacyPos.Api.Catalogue.Medicine", "Medicine")
                        .WithMany("Batches")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("PharmacyPos.Api.Catalogue.MedicineIngredient", b =>
                {
                    b.HasOne("PharmacyPos.Api.Catalogue.GenericIngredient", "GenericIngredient")
                        .WithMany()
                        .HasForeignKey("GenericIngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmacyPos.Api.Catalogue.Medicine", "Medicine")
                        .WithMany("Ingredients")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GenericIngredient");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("PharmacyPos.Api.Sales.ChargeMedicine", b =>
                {
                    b.HasOne("PharmacyPos.Api.Sales.ChargeRule", "ChargeRule")
                        .WithMany("Medicines")
                        .HasForeignKey("ChargeRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmacyPos.Api.Catalogue.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChargeRule");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("PharmacyPos.Api.Sales.ChargeRule", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("StoppedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PharmacyPos.Api.Sales.OfferRule", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmacyPos.Api.Catalogue.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("StoppedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("PharmacyPos.Api.Stock.ReceivingMovement", b =>
                {
                    b.HasOne("PharmacyPos.Api.Catalogue.MedicineBatch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("PostedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmacyPos.Api.Stock.StockReceiptRevision", "Revision")
                        .WithMany()
                        .HasForeignKey("RevisionId", "ReceiptId")
                        .HasPrincipalKey("Id", "ReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("PharmacyPos.Api.Stock.StockDisposal", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("DisposedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmacyPos.Api.Stock.StockReceipt", "Receipt")
                        .WithMany()
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("PharmacyPos.Api.Stock.StockExportEvent", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmacyPos.Api.Stock.StockReceiptRevision", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmacyPos.Api.Catalogue.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("MrpVerifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PharmacyPos.Api.Stock.StockReceipt", "Receipt")
                        .WithMany("Revisions")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Medicine");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("PharmacyPos.Api.Stock.StockReviewEvent", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmacyPos.Api.Stock.StockReceiptRevision", "Revision")
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("PharmacyPos.Api.Catalogue.Medicine", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("PharmacyPos.Api.Sales.ChargeRule", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("PharmacyPos.Api.Stock.StockReceipt", b =>
                {
                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
