import { useState } from 'react'
import { stockGet, stockExport } from './stockApi'
type Report = { from: string; to: string; generatedAt: string; complete: boolean; salesCount: number; returnedLines: number; restockedLines: number; salesPaid: number; refundsPaid: number; excludedSalesCharges: number | null; excludedRefundCharges: number | null; netIncome: number | null; costOfSales: number | null; recoveredCost: number | null; netCost: number | null; grossProfit: number | null; issues: { kind: string; id: string; description: string }[] }
const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Dhaka', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date())
const money = (v: number | null) => v === null ? 'Incomplete' : `৳${v.toLocaleString('en-BD', { minimumFractionDigits: 2, maximumFractionDigits: 6 })}`
export function ProfitReport({ onBack }: { onBack: () => void }) {
  const [from, setFrom] = useState(today), [to, setTo] = useState(today), [data, setData] = useState<Report | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState('')
  return <><div className="page-heading"><div><p className="eyebrow">ADMIN</p><h1>Profit report</h1><p>Gross profit from sales and returns, before shop expenses.</p></div><button onClick={onBack}>Medicine catalogue</button></div>
    <form className="catalogue-panel charge-form" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); setData(null); try { setData(await stockGet<Report>(`/api/reports/profit?${new URLSearchParams({ from, to })}`)) } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }}><fieldset className="charge-fields" disabled={busy}><label>From date<input required type="date" min="2000-01-01" max={to} value={from} onInput={e => setFrom(e.currentTarget.value)} /></label><label>To date<input required type="date" min={from} value={to} onInput={e => setTo(e.currentTarget.value)} /></label><button className="primary">{busy ? 'Loading…' : 'View profit report'}</button></fieldset><p>Both dates included, in Bangladesh time. Up to 366 days.</p></form>
    {error && <p role="alert" className="auth-error">{error}</p>}
    {data && <section className="catalogue-panel charge-form"><h2>{data.from} to {data.to}</h2><p>Generated {new Date(data.generatedAt).toLocaleString('en-GB', { timeZone: 'Asia/Dhaka' })} · Bangladesh time</p><h2>{data.complete ? `Gross profit: ${money(data.grossProfit)}` : 'Profit incomplete — review the items below'}</h2>
      <button disabled={busy} onClick={async () => { setBusy(true); setError(''); try { await stockExport(`/api/reports/profit?${new URLSearchParams({ from: data.from, to: data.to, format: 'csv' })}`, `profit-${data.from}-${data.to}.csv`) } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }}>Export profit CSV</button><p className="field-help">Export recalculates these dates using the latest costs and classifications. Incomplete amounts are blank in the CSV, never zero.</p>
      <p>{data.salesCount} completed sales · {data.returnedLines} refunded receipt items · {data.restockedLines} returned items approved for resale</p>
      <dl className="report-totals">{([
        ['Customer payments', data.salesPaid], ['Customer refunds', data.refundsPaid], ['Excluded charges collected', data.excludedSalesCharges], ['Excluded charges refunded', data.excludedRefundCharges], ['Net pharmacy income', data.netIncome], ['Purchase cost of stock sold', data.costOfSales], ['Cost recovered through resale approval', data.recoveredCost], ['Net stock cost', data.netCost], ['Gross profit', data.grossProfit],
      ] as [string, number | null][]).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{money(value)}</dd></div>)}</dl>
      {data.issues.length > 0 && <><h3>Needs review ({data.issues.length})</h3><p>Add missing delivery costs in Purchase costs, and review unclassified charges in Cart charges. Then reload this report.</p>{data.issues.map(i => <p key={`${i.kind}-${i.id}`}><strong>{i.kind}:</strong> {i.description} · Reference {i.id}</p>)}</>}
      <h3>How this is calculated</h3><p>Net income = customer payments − excluded charges collected − customer refunds + excluded charges refunded. Discounts are already included in customer payments.</p><p>Gross profit = net income − purchase cost of stock sold + cost recovered through resale approval.</p>
      <p>Refunds reduce income on their issue date. Returned stock only recovers cost on the date an admin approves it for resale. Held or disposed returns do not recover cost.</p>
      <p>The latest corrected purchase costs and charge classifications apply to earlier periods. Receipt rounding is shared proportionally between income and excluded charges. Amounts are displayed to six decimal places where needed.</p>
      <p>This report excludes rent, salaries and other shop expenses. Unsold inventory write-offs are not included. It is not a cash balance or tax filing report.</p>
    </section>}
  </>
}
