import { useEffect, useRef, useState } from 'react'
import { stockGet, stockPost, stockExport } from './stockApi'

type SaleLookup = { canReturn: boolean; returnDeadline: string; saleId: string; receiptNumber: string; total: number; lines: { index: number; refund: number; originalPayments: { method: string; amount: number }[]; alreadyReturned: boolean; details: { brandName: string; batchNumber: string; quantity: number; unit: string; baseUnits: number; baseUnit: string } }[] }
type RefundInput = { requestId: string; saleId: string; lineIndexes: number[]; reason: string; itemsReceived: boolean; cashRefunded: boolean; receiptPresented: boolean; refundDestination?: string; paymentReferences?: { method: string; reference: string }[] }
type ReturnRecord = { payments: { method: string; amount: number; reference: string | null }[]; refundDestination: string; receiptPresented: boolean | null; id: string; receiptNumber: string; amount: number; method: string; reason: string; actorName: string; at: string; items: { id: string; brandName: string; batchNumber: string; packs: number; unit: string; quantity: number; baseUnit: string; refund: number; status: string; reviewerName: string | null; reviewReason: string | null; reviewedAt: string | null }[] }
type StockItem = { id: string; brandName: string; batchNumber: string; quantity: number; baseUnit: string; expiryDate: string; status: string; returnedBy: string; returnedAt: string; reason: string; reviewerName: string | null; reviewedAt: string | null; reviewReason: string | null }
const money = (v: number) => `৳${v.toLocaleString('en-BD',{minimumFractionDigits:2,maximumFractionDigits:2})}`
export function ReturnsWorkspace({ isAdmin, username, onBack }: { isAdmin: boolean; username: string; onBack: () => void }) {
  const storageKey = `pharmacy-return:${username}`
  const [pending, setPending] = useState<RefundInput | null>(() => { try { return JSON.parse(sessionStorage.getItem(storageKey) || 'null') as RefundInput | null } catch { return null } })
  const [tab, setTab] = useState('new'), [refresh, setRefresh] = useState(0), [error, setError] = useState('')
  function clear() { sessionStorage.removeItem(storageKey); setPending(null); setRefresh(v => v + 1) }
  if (pending) return <RefundPending input={pending} onDone={() => { clear(); setTab('history') }} onRejected={clear} />
  return <><div className="page-heading"><div><p className="eyebrow">RETURNS</p><h1>Returns and refunds</h1></div><button onClick={onBack}>Back to counter</button></div>
    <p className="notice">Return complete receipt items only. Refunds need no admin approval. Returned medicines are held separately until an admin approves resale.</p>
    <div className="heading-actions"><button onClick={() => setTab('new')}>New return</button><button onClick={() => setTab('history')}>Return history</button><button onClick={() => setTab('stock')}>Returned stock</button></div>
    {error && <p role="alert" className="auth-error">{error}</p>}
    {tab === 'new' ? <ReturnForm key={refresh} onBegin={input => { try { sessionStorage.setItem(storageKey,JSON.stringify(input)); setPending(input); setError('') } catch { setError('Allow browser storage to keep a safe refund reference before continuing.') } }} /> : tab === 'history' ? <ReturnHistory /> : <ReturnedStock isAdmin={isAdmin} />}
  </>
}
function ReturnForm({ onBegin }: { onBegin: (input: RefundInput) => void }) {
  const [number, setNumber] = useState(''), [sale, setSale] = useState<SaleLookup | null>(null), [selected, setSelected] = useState<number[]>([])
  const [destination, setDestination] = useState('Original'), [references, setReferences] = useState<Record<string, string>>({})
  const [presented, setPresented] = useState(false)
  const [reason, setReason] = useState(''), [received, setReceived] = useState(false), [cash, setCash] = useState(false), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const retry = useRef<{ key: string; input: RefundInput } | null>(null)
  const total = sale ? Math.round(sale.lines.filter(l => selected.includes(l.index)).reduce((sum,l) => sum + l.refund,0)*100)/100 : 0
  const original = new Map<string, number>()
  sale?.lines.filter(l => selected.includes(l.index)).forEach(l => l.originalPayments.forEach(p => original.set(p.method, (original.get(p.method) ?? 0) + Math.round(p.amount * 100))))
  const payments = destination === 'Cash' ? [{ method: 'Cash', amount: total }] : [...original].map(([method, amount]) => ({ method, amount: amount / 100 }))
  const referencesValid = payments.every(p => p.method === 'Cash' || !!references[p.method]?.trim())
  return <section className="catalogue-panel charge-form"><form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); setSale(null); setReferences({}); setDestination('Original'); setSelected([]); setReceived(false); setCash(false); setPresented(false); try { setSale(await stockGet<SaleLookup>(`/api/returns/sale?number=${encodeURIComponent(number.trim())}`)) } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }}>
    <div className="field"><label htmlFor="return-receipt">Original receipt number</label><input id="return-receipt" required maxLength={32} placeholder="POS-00000001" value={number} onChange={e => setNumber(e.target.value)} /></div><button disabled={busy}>Find receipt</button>
  </form>{error && <p role="alert" className="auth-error">{error}</p>}
    {sale && <form onSubmit={e => { e.preventDefault(); if (!referencesValid || !sale.canReturn || !presented || !received || !cash || selected.length === 0) return; const payload = { saleId: sale.saleId, lineIndexes: [...selected].sort((a,b) => a-b), reason: reason.trim(), itemsReceived: received, cashRefunded: cash, receiptPresented: presented, refundDestination: destination, paymentReferences: payments.filter(p => p.method !== 'Cash').map(p => ({ method: p.method, reference: references[p.method].trim() })) }; const key = JSON.stringify(payload); if (retry.current?.key !== key) retry.current = { key, input: { ...payload, requestId: crypto.randomUUID() } }; onBegin(retry.current.input) }}>
      <h2>{sale.receiptNumber}</h2><p>Return deadline: {new Date(sale.returnDeadline).toLocaleString('en-GB', { timeZone: 'Asia/Dhaka' })} (Bangladesh time)</p>{!sale.canReturn && <p role="alert" className="auth-error">The 15-day return/refund period has ended. Do not issue a refund.</p>}<p>Original bill paid: {money(sale.total)}</p>
      {sale.lines.map(l => <article className="counter-product" key={l.index}><label><input type="checkbox" disabled={!sale.canReturn || l.alreadyReturned} checked={selected.includes(l.index)} onChange={e => { setSelected(rows => e.target.checked ? [...rows,l.index] : rows.filter(i => i !== l.index)); setCash(false); setReceived(false); setReferences({}) }} /> <strong>{l.details.brandName}</strong> · {l.details.quantity} {l.details.unit.toLowerCase()} · Batch {l.details.batchNumber}</label><p>{l.details.baseUnits} {l.details.baseUnit.toLowerCase()}s · {l.alreadyReturned ? 'Already returned' : `Full item refund: ${money(l.refund)}`}</p></article>)}
      <p className="field-help">Amounts include the original discounts, charges and allocated rounding. They do not use current prices. All items together refund exactly the original total.</p>
      <h3>Refund: {money(total)}</h3>
      <label>Refund destination<select value={destination} onChange={e => { setDestination(e.target.value); setReferences({}); setCash(false) }}><option value="Original">Original payment methods</option><option value="Cash">Cash</option></select></label>
      <p className="field-help">For original methods, the refund uses each selected item's share of the original payments, including rounding. Complete the refund outside the POS before recording it.</p>
      {payments.map(p => <div key={p.method}><p><strong>{p.method}: {money(p.amount)}</strong></p>{p.method !== 'Cash' && <label>{p.method} refund reference<input required maxLength={100} autoComplete="off" value={references[p.method] ?? ''} onChange={e => { setReferences(previous => ({ ...previous, [p.method]: e.target.value })); setCash(false) }} /></label>}</div>)}<div className="field"><label htmlFor="return-reason">Return reason</label><textarea id="return-reason" required maxLength={1000} value={reason} onChange={e => setReason(e.target.value)} /></div>
      <p><label><input type="checkbox" required checked={presented} onChange={e => setPresented(e.target.checked)} /> The customer presented the original receipt.</label></p>
      <p><label><input type="checkbox" required checked={received} onChange={e => setReceived(e.target.checked)} /> I have received the complete quantity of every selected receipt item.</label></p>
      <p><label><input type="checkbox" required checked={cash} onChange={e => setCash(e.target.checked)} /> I have completed the {money(total)} refund using the methods shown above.</label></p>
      <button className="primary" disabled={!referencesValid || !sale.canReturn || !presented || !received || !cash || !selected.length}>Record return and refund</button>
    </form>}
  </section>
}
function RefundPending({ input, onDone, onRejected }: { input: RefundInput; onDone: () => void; onRejected: () => void }) {
  const [record, setRecord] = useState<ReturnRecord | null>(null), [error, setError] = useState(''), [rejected, setRejected] = useState(false), [busy, setBusy] = useState(true), [retry, setRetry] = useState(0)
  useEffect(() => { let active = true; async function send() {
    try { const session = await stockGet<{ csrfToken: string }>('/api/auth/session'); const r = await fetch('/api/returns',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':session.csrfToken},body:JSON.stringify(input),signal:AbortSignal.timeout(20000)}); const data = await r.json().catch(() => null); if (!active) return; if (r.ok && data?.items) setRecord(data); else { setRejected([400,404,409].includes(r.status)); setError(data?.message || 'Refund result is not confirmed. Retry the same reference; do not issue the refund again.') } }
    catch { if (active) setError('Connection failed. Retry this same refund reference; do not issue the refund again.') } finally { if (active) setBusy(false) }
  } void send(); return () => { active = false } },[input,retry])
  return <section className="catalogue-panel charge-form"><h1>{record ? 'Return and refund recorded' : busy ? 'Recording refund…' : 'Refund needs attention'}</h1><p>Reference: {input.requestId}</p>{record ? <><ReturnCard record={record} /><button onClick={onDone}>View return history</button></> : <>{error && <p role="alert" className="auth-error">{error}</p>}{!busy && (rejected ? <button onClick={onRejected}>Reload receipt and check history</button> : <button onClick={() => { setBusy(true); setError(''); setRetry(v => v + 1) }}>Retry same refund</button>)}</>}</section>
}
function ReturnCard({ record }: { record: ReturnRecord }) {
  return <article className="counter-product"><h3>{record.receiptNumber} · {money(record.amount)} refunded ({record.method})</h3><p>By {record.actorName} · {new Date(record.at).toLocaleString()}</p><p>{record.reason}</p>{record.payments?.map((p, i) => <p key={i}>{p.method}: {money(p.amount)}{p.reference && ` · Reference: ${p.reference}`}</p>)}<p>Original receipt: {record.receiptPresented ? 'Presented and confirmed' : 'Not recorded for this historical return'}</p>{record.items.map(i => <div key={i.id}><p><strong>{i.brandName}</strong> · Batch {i.batchNumber} · {i.packs} {i.unit.toLowerCase()} ({i.quantity} {i.baseUnit.toLowerCase()}s) · {money(i.refund)} · {i.status}</p>{i.reviewedAt && <p>{i.reviewerName} · {new Date(i.reviewedAt).toLocaleString()} · {i.reviewReason}</p>}</div>)}</article>
}
function ReturnHistory() {
  const [page, setPage] = useState(1), [data, setData] = useState<{ items: ReturnRecord[]; hasMore: boolean } | null>(null), [error, setError] = useState('')
  useEffect(() => { const controller = new AbortController(); void stockGet<NonNullable<typeof data>>(`/api/returns?page=${page}`,controller.signal).then(setData).catch(e => { if (!controller.signal.aborted) setError(e.message) }); return () => controller.abort() },[page])
  return <section className="catalogue-panel charge-form"><h2>Return and refund history</h2>{error && <p role="alert">{error}</p>}{!data ? <p>Loading history…</p> : <>{!data.items.length && <p>No returns recorded.</p>}{data.items.map(r => <ReturnCard key={r.id} record={r} />)}<div className="pagination"><button disabled={page === 1} onClick={() => { setData(null); setPage(p => p-1) }}>Previous</button><span>Page {page}</span><button disabled={!data.hasMore} onClick={() => { setData(null); setPage(p => p+1) }}>Next</button></div></>}</section>
}
function ReturnedStock({ isAdmin }: { isAdmin: boolean }) {
  const [status, setStatus] = useState('Held'), [page, setPage] = useState(1), [refresh, setRefresh] = useState(0), [error, setError] = useState(''), [data, setData] = useState<{ items: StockItem[]; hasMore: boolean } | null>(null)
  useEffect(() => { const controller = new AbortController(); void stockGet<NonNullable<typeof data>>(`/api/returns/stock?status=${status}&page=${page}`,controller.signal).then(setData).catch(e => { if (!controller.signal.aborted) setError(e.message) }); return () => controller.abort() },[status,page,refresh])
  return <section className="catalogue-panel charge-form"><h2>Returned-stock inventory</h2><div className="heading-actions"><select aria-label="Returned-stock status" value={status} onChange={e => { setData(null); setStatus(e.target.value); setPage(1) }}><option value="Held">Held — not sellable</option><option value="Restocked">Approved for resale</option><option value="Disposed">Disposed (last 3 months)</option></select><button onClick={() => { setData(null); setError(''); setRefresh(v => v+1) }}>Refresh returned stock</button>{isAdmin && status === 'Disposed' && <button onClick={async () => { try { await stockExport('/api/returns/disposals/export','disposed-returns.csv') } catch (e) { setError((e as Error).message) } }}>Export disposal CSV</button>}</div>
    {error && <p role="alert">{error}</p>}{!data ? <p>Loading returned stock…</p> : <>{!data.items.length && <p>No items in this list.</p>}{data.items.map(i => <article className="counter-product" key={i.id}><h3>{i.brandName} · {i.quantity} {i.baseUnit.toLowerCase()}s</h3><p>Batch {i.batchNumber} · Expires {i.expiryDate} · {i.status}</p><p>Returned by {i.returnedBy} · {new Date(i.returnedAt).toLocaleString()} · {i.reason}</p>{i.reviewedAt && <p>Reviewed by {i.reviewerName} · {new Date(i.reviewedAt).toLocaleString()} · {i.reviewReason}</p>}{isAdmin && i.status === 'Held' && <StockReview item={i} onSaved={() => { setData(null); setRefresh(v => v+1) }} />}</article>)}<div className="pagination"><button disabled={page === 1} onClick={() => { setData(null); setPage(p => p-1) }}>Previous</button><span>Page {page}</span><button disabled={!data.hasMore} onClick={() => { setData(null); setPage(p => p+1) }}>Next</button></div></>}
  </section>
}
function StockReview({ item, onSaved }: { item: StockItem; onSaved: () => void }) {
  const [action, setAction] = useState('Restocked'), [reason, setReason] = useState(''), [checked, setChecked] = useState(false), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  return <form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { await stockPost(`/api/returns/stock/${item.id}/review`,{action,reason,checked}); onSaved() } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }}><fieldset disabled={busy} className="charge-fields"><label>Admin action<select value={action} onChange={e => { setAction(e.target.value); setChecked(false) }}><option value="Restocked">Approve for resale</option><option value="Disposed">Record physical disposal</option></select></label><label>Inspection / disposal reason<textarea required maxLength={1000} value={reason} onChange={e => setReason(e.target.value)} /></label><label><input type="checkbox" required checked={checked} onChange={e => setChecked(e.target.checked)} /> {action === 'Restocked' ? 'I have inspected the full returned item and confirmed it is suitable for resale.' : 'I have physically disposed of the full returned item.'}</label><button className="primary">{busy ? 'Saving…' : action === 'Restocked' ? 'Approve returned stock' : 'Record disposal'}</button></fieldset>{error && <p role="alert" className="auth-error">{error}</p>}</form>
}
