import { useEffect, useRef, useState } from 'react'
import { stockGet, stockPost } from './stockApi'
type Row = { medicineId: string; brandName: string; manufacturer: string; baseUnit: string; minimum: number | null; version: string; availableUnits: number }
type Lot = { lotId: string; brandName: string; manufacturer: string; baseUnit: string; batchNumber: string; expiryDate: string; daysRemaining: number; remainingUnits: number; sellable: boolean }
type Result = { items: (Row | Lot)[]; hasMore: boolean; checkedAt: string }
export function StockAlerts({ isAdmin, onBack, backLabel = 'Medicine catalogue' }: { isAdmin: boolean; onBack: () => void; backLabel?: string }) {
  const [tab, setTab] = useState('low'), [search, setSearch] = useState(''), [page, setPage] = useState(1), [refresh, setRefresh] = useState(0)
  return <><div className="page-heading"><div><p className="eyebrow">INVENTORY</p><h1>Stock alerts</h1><p>Low stock and batches expiring within 90 days.</p></div><button onClick={onBack}>{backLabel}</button></div>
    <section className="catalogue-panel charge-form"><nav className="stock-tabs" aria-label="Alert views">{[['low', 'Low stock'], ['expiry', 'Near expiry'], ...(isAdmin ? [['settings', 'Set minimum stock']] : [])].map(([key, label]) => <button key={key} aria-pressed={tab === key} onClick={() => { setTab(key); setPage(1) }}>{label}</button>)}</nav>
      <label>Search medicine{tab === 'expiry' ? ' or batch' : ''}<input type="search" value={search} maxLength={100} onChange={e => { setSearch(e.target.value); setPage(1) }} /></label><button onClick={() => setRefresh(v => v + 1)}>Refresh alerts</button>
      <p>{tab === 'expiry' ? 'Approved deliveries with remaining stock, from today through 90 days ahead in Bangladesh time. Already expired stock is in unsellable inventory. Held customer returns remain in returned-stock inventory.' : 'An alert appears when sellable stock is at or below the configured minimum. Quantities use individual tablets, capsules, bottles or other base units. Medicines without a minimum are not monitored.'}</p>
      <AlertList key={`${tab}-${search}-${page}-${refresh}`} tab={tab} search={search} page={page} onPage={setPage} onSaved={() => setRefresh(v => v + 1)} />
    </section>
  </>
}
function AlertList({ tab, search, page, onPage, onSaved }: { tab: string; search: string; page: number; onPage: (n: number) => void; onSaved: () => void }) {
  const [data, setData] = useState<Result | null>(null), [error, setError] = useState('')
  useEffect(() => { const c = new AbortController(); const load = () => void stockGet<Result>(`/api/stock-alerts/${tab === 'expiry' ? 'expiry' : 'low'}?${new URLSearchParams({ search, page: String(page), all: String(tab === 'settings') })}`, c.signal).then(d => { setData(d); setError('') }).catch(e => { if (!c.signal.aborted) setError(e.message) }); const delay = window.setTimeout(load, 200); const timer = window.setInterval(load, 60000); return () => { c.abort(); window.clearTimeout(delay); window.clearInterval(timer) } }, [tab, search, page])
  if (error) return <p role="alert">{error}</p>
  if (!data) return <p>Loading stock alerts…</p>
  return <><p className="field-help">Checked {new Date(data.checkedAt).toLocaleString('en-GB', { timeZone: 'Asia/Dhaka' })} (Bangladesh time). Refreshes every minute while open.</p>{!data.items.length && <p>{tab === 'settings' ? 'No matching approved medicines.' : tab === 'low' ? 'No low-stock alerts. Only medicines with a configured minimum are monitored.' : 'No near-expiry stock in this view.'}</p>}
    {data.items.map(item => tab === 'expiry' ? <ExpiryCard key={(item as Lot).lotId} lot={item as Lot} /> : <ThresholdCard key={`${(item as Row).medicineId}-${(item as Row).version}`} row={item as Row} editable={tab === 'settings'} onSaved={onSaved} />)}
    <nav className="pagination"><button disabled={page === 1} onClick={() => onPage(page - 1)}>Previous</button><span>Page {page}</span><button disabled={!data.hasMore} onClick={() => onPage(page + 1)}>Next</button></nav></>
}
function ExpiryCard({ lot: l }: { lot: Lot }) { return <article className="counter-product"><h2>{l.brandName} · Batch {l.batchNumber}</h2><p>{l.manufacturer}</p><p><strong>{l.daysRemaining === 0 ? 'Expires today' : `Expires in ${l.daysRemaining} days`}</strong> · {l.expiryDate}</p><p>{l.remainingUnits.toLocaleString()} {l.baseUnit.toLowerCase()}s remaining · {l.sellable ? 'Sellable' : 'Held — medicine or MRP approval required'}</p></article> }
function ThresholdCard({ row: r, editable, onSaved }: { row: Row; editable: boolean; onSaved: () => void }) {
  const [open, setOpen] = useState(false), [history, setHistory] = useState<{ id: string; minimum: number | null; previousMinimum: number | null; actorName: string; at: string; reason: string }[] | null>(null), [error, setError] = useState('')
  return <article className="counter-product"><h2>{r.brandName}</h2><p>{r.manufacturer}</p><p><strong>{r.availableUnits.toLocaleString()} sellable {r.baseUnit.toLowerCase()}s</strong> · Minimum: {r.minimum === null ? 'Not set — no alert' : r.minimum.toLocaleString()}</p>{r.minimum !== null && r.availableUnits <= r.minimum && <p className="auth-error">{r.availableUnits === 0 ? 'Out of sellable stock' : 'At or below minimum stock'}</p>}
    {editable && <><div className="heading-actions"><button onClick={() => setOpen(v => !v)}>{open ? 'Cancel threshold change' : 'Set minimum'}</button><button onClick={async () => { try { setHistory(await stockGet(`/api/stock-alerts/${r.medicineId}/history`)); setError('') } catch (e) { setError((e as Error).message) } }}>Threshold history</button></div>{open && <ThresholdForm row={r} onSaved={onSaved} />}</>}
    {error && <p role="alert">{error}</p>}{history && <div><h3>Latest 50 threshold changes</h3>{!history.length && <p>No changes recorded.</p>}{history.map(h => <p key={h.id}>{h.previousMinimum ?? 'Not set'} → {h.minimum ?? 'Not set'} · {h.actorName} · {new Date(h.at).toLocaleString()} · {h.reason}</p>)}</div>}
  </article>
}
function ThresholdForm({ row: r, onSaved }: { row: Row; onSaved: () => void }) {
  const [enabled, setEnabled] = useState(r.minimum !== null), [value, setValue] = useState(r.minimum === null ? '' : String(r.minimum)), [reason, setReason] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const request = useRef(crypto.randomUUID()); const edited = () => { request.current = crypto.randomUUID() }
  return <form onSubmit={async e => { e.preventDefault(); setError(''); setBusy(true); try { await stockPost(`/api/stock-alerts/${r.medicineId}/threshold`, { requestId: request.current, expectedVersion: r.version, minimum: enabled ? Number(value) : null, reason }); onSaved() } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }}><fieldset disabled={busy} className="charge-fields"><label><input type="checkbox" checked={enabled} onChange={e => { setEnabled(e.target.checked); edited() }} /> Monitor low stock for this medicine</label>{enabled && <label>Minimum individual {r.baseUnit.toLowerCase()}s<input type="number" required min="0" max="1000000000" step="1" value={value} onChange={e => { setValue(e.target.value); edited() }} /></label>}<p>Use 0 for out-of-stock alerts only. Uncheck monitoring to disable this medicine’s low-stock alert.</p><label>Reason<textarea required maxLength={1000} value={reason} onChange={e => { setReason(e.target.value); edited() }} /></label><button className="primary">{busy ? 'Saving…' : 'Save minimum stock'}</button></fieldset>{error && <p role="alert">{error}</p>}</form>
}
